import { injectReadingAid } from '../server/src/render/render.util';

/**
 * The framed-guide half of the reading aid.
 *
 * A study guide's `index.html` build and a tutor deck are both served verbatim
 * to an iframe, so nothing the page shell does can reach their prose. The aid
 * has to be spliced into the framed document itself — and it is served from
 * this repo rather than vendored per guide, so one copy governs every guide the
 * app frames, however old the build is.
 */
describe('injectReadingAid', () => {
  it('links the aid stylesheet in the head and loads its script at the end of the body', () => {
    const out = injectReadingAid('<!doctype html><html><head><title>G</title></head><body><p>hi</p></body></html>');

    expect(out).toContain('<link rel="stylesheet" href="/bionic.css">');
    expect(out).toContain('<script src="/bionic.js"></script>');
    // Placement is the contract, not an accident: the stylesheet belongs in the
    // head so it is parsed before first paint, and the script at the end of the
    // body so its ready branch finds the prose already in the DOM.
    expect(out.indexOf('/bionic.css')).toBeLessThan(out.indexOf('</head>'));
    expect(out.indexOf('<p>hi</p>')).toBeLessThan(out.indexOf('/bionic.js'));
    expect(out.indexOf('/bionic.js')).toBeLessThan(out.indexOf('</body>'));
  });

  it('leaves a build that already carries its own copy of the aid untouched', () => {
    // Guides generated by the current study skill inline the aid themselves. A
    // second copy would decorate an already-decorated tree — each script keeps
    // its own `bound` flag, so neither one stops the other.
    const own = '<html><head><style>/* bionic v2 */</style></head><body><p>hi</p></body></html>';

    expect(injectReadingAid(own)).toBe(own);
  });

  it('injects into a document that has no head or body tags', () => {
    // Hand-written and older generated builds are not always well-formed. The
    // aid is the point of the route; dropping it because a tag is missing would
    // reintroduce exactly the silence this fixes.
    const out = injectReadingAid('<h1>Deck</h1>');

    expect(out).toContain('/bionic.css');
    expect(out).toContain('/bionic.js');
    expect(out).toContain('<h1>Deck</h1>');
  });
});
